# Generated by Django 2.2.1 on 2019-05-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insuranceNumber', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('firstName', models.CharField(max_length=255)),
                ('yearOfBirth', models.CharField(max_length=255)),
                ('cityOfBirth', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
            ],
        ),
    ]
